config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  
  resources :events, only: [:index, :create, :new, :edit, :show, :update, :destroy] do
    get 'nav_month', on: :collection
    get :date_events, on: :collection
    get :photos_count, on: :member
    resources :list_photos, only: [:index], on: :member do
      get :details, on: :member
      post :drop, on: :collection
      get :reload_image_container, on: :collection
      get :display_locations, on: :collection
    end
    # eventsリソース内にphotosリソースをネストし、destroyアクションを追加
    resources :photos, only: [:destroy]
  end

  # search コントローラーの index アクションは検索画面を表示します。
  resources :search, only: [:index] do
    # 検索を実行するカスタムアクション。collection を使っています。
    collection do
      post :execute_search
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def execute_search
    @photos = Photo.search(search_params)
    # Ajaxリクエストに対するレスポンスとしてHTMLを返す
    render partial: "search_results", locals: { photos: @photos }, formats: [:html]
  end

  private

  def search_params
    params.permit(:start_date, :end_date, :event_name, :'camera-make', :'camera-model', :'lens-make', :'lens-model')
  end
  
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_search_results.html.erb
<!-- app/views/search/_search_results.html.erb -->
<% photos.each do |photo| %>
  <tr data-event-id="<%= photo.event.id %>">
    <td><img src="<%= photo.thumbnail %>" alt="Thumbnail"></td>
    <td><%= DateTime.parse(photo.date_time).strftime('%Y-%m-%d') %></td>
    <td><%= photo.event.name %></td>
    <td><%= photo.camera_model.camera_make.display_name %></td>
    <td><%= photo.camera_model.display_name %></td>
    <td><%= photo.lens_model.lens_make.display_name %></td>
    <td><%= photo.lens_model.display_name %></td>
  </tr>
<% end %>

app/views/search/index.html.erb
<%# content_for :head do %>
  <%= stylesheet_link_tag 'search', media: 'all', 'data-turbolinks-track': 'reload' %>
<%# end %>

<%= render "shared/header" %>

<div class="center-container">
  <div class="container">
    <div class="search-condition">
      <%= form_with id: 'search-form', url: execute_search_search_index_path, method: :post, local: false do |f| %>
        <table class="condition-table">
          <tr>
            <td class="condition-first-row" colspan="4">
              <%= f.date_field :start_date, id: 'start_date' %>
              <span>から</span>
              <%= f.date_field :end_date, id: 'end_date' %>
              <span>イベント名：</span>
              <%= f.text_field :event_name, id: 'event_name' %>
            <td>
            <td class="search_button" rowspan="3">
              <%= f.submit '検索実行', id: 'search_button' %>
            </td>
            <td class="reset_conditions_button" rowspan="3">
              <%= button_tag 'リセット', type: 'button', id: 'reset_conditions_button' %>
            </td>
          </tr>
          <tr>
            <td>
               <%= f.select :camera_make, 
                options_for_select([['-カメラメーカ-', 0]] + CameraMake.all.map { |camera_make| [camera_make.display_name, camera_make.id] }),
                {}, { id: 'camera-make' } %>
            </td>
            <td colspan="3">
              <%= f.select :camera_model, 
                options_for_select([['-カメラモデル-', 0]] + CameraModel.all.map { |camera_model| [camera_model.display_name, camera_model.id] }),
                {}, { id: 'camera-model' } %>
            </td>
          </tr>
          <tr>
            <td>
              <%= f.select :lens_make, 
                options_for_select([['-レンズメーカ-', 0]] + LensMake.all.map { |lens_make| [lens_make.display_name, lens_make.id] }),
                {}, { id: 'lens-make' } %>
            </td>
            <td colspan="3">
              <%= f.select :lens_model, 
                options_for_select([['-レンズモデル-', 0]] + LensModel.all.map { |lens_model| [lens_model.display_name, lens_model.id] }),
                {}, { id: 'lens-model' } %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>
    <div class="results-container">
      <table id="results" class="results">
        <thead>
          <tr>
            <th>サムネイル</th>
            <th>撮影日</th>
            <th>イベント</th>
            <th>カメラMaker</th>
            <th>カメラModel</th>
            <th>レンズMaker</th>
            <th>レンズModel</th>
          </tr>
        </thead>
        <tbody id="search-results" class="tbody-container">
        </tbody>
      </table>
    </div>
    <div class="search-operations">
      <div class="space-operation"></div>
      <button id="photo-operation">写　真</button>
      <button id="reset-operation">リセット</button>
    </div>
  </div>
</div>

<%= javascript_include_tag "search" %>